spring.application.name=ExpenseSharingApp



# H2 Database
spring.datasource.url=jdbc:h2:mem:spliteasy_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=999086687983-ghec371uaf39r676p41c61ifm7ipdv4j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


#swagger 
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Show info+warn+error globally
logging.level.root=INFO

# Show debug for specific package
logging.level.com.spliteasy.expense_sharing.service=DEBUG

jwt.secret=secret1234567890secret1234567890
jwt.expiration-ms=3600000  # 1 hour in milliseconds